# Generated by Django 6.0.2 on 2026-03-09 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('boys', 'boys'), ('girls', 'girls')], max_length=10)),
                ('total_capacity', models.PositiveIntegerField()),
                ('occupied', models.PositiveIntegerField()),
                ('curfew', models.CharField(max_length=30)),
                ('warden_name', models.CharField(max_length=120)),
                ('warden_init', models.CharField(max_length=4)),
                ('warden_phone', models.CharField(max_length=40)),
                ('warden_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HostelFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='hostel.hostel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
