# Generated by Django 6.0.2 on 2026-03-09 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('notes', 'notes'), ('pyq', 'pyq')], default='notes', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=120)),
                ('year', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='studyhub/')),
                ('file_type', models.CharField(default='pdf', max_length=10)),
                ('file_size', models.CharField(blank=True, default='', max_length=20)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('exam_year', models.CharField(blank=True, default='', max_length=10)),
                ('exam_type', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
